export const RATE_LIMIT_MODULE_OPTIONS = Symbol('RATE_LIMIT_MODULE_OPTIONS');

export const RATE_LIMIT_STORE = Symbol('RATE_LIMIT_STORE');

export const RATE_LIMIT_METADATA = Symbol('RATE_LIMIT_METADATA');

export const RATE_LIMIT_METRICS = Symbol('RATE_LIMIT_METRICS');

export const RATE_LIMIT_RULE_RESOLVER = Symbol('RATE_LIMIT_RULE_RESOLVER');
